Repository ultralytics/thop, pull requests merged in 2024-11, with the labels that each got.

#70 Add environment to publish.yml
  .github/workflows/publish.yml
  thop/__init__.py
Labels: devops

#71 Update publish.yml to PyPI
  .github/workflows/publish.yml
Labels: devops

#72 Fix PyPI downloads links
  README.md
Labels: documentation

#73 Slack v2 API usage
  .github/workflows/publish.yml
  thop/__init__.py
Labels: enhancement, devops
