Repository ultralytics/thop, pull requests merged in 2024-10, with the labels that each got.

#60 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
Labels: documentation, enhancement

#63 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
Labels: documentation, enhancement

#64 Update publish.yml to trusted publisher
  .github/workflows/publish.yml
  thop/__init__.py
Labels: dependencies, enhancement

#66 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#67 Update publish.yml
  .github/workflows/publish.yml
  pyproject.toml
Labels: enhancement

#68 Python 3.13 update
  pyproject.toml
  thop/__init__.py
Labels: dependencies, enhancement

#69 Update publish.yml
  .github/workflows/publish.yml
Labels: devops
