Repository ultralytics/thop, pull requests merged in 2024-08, with the labels that each got.

#35 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: dependencies, enhancement

#37 v2.0.1 - updated classifiers
  thop/__init__.py
Labels: dependencies

#38 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#39 Update pyproject.toml classifiers
  .github/workflows/publish.yml
  pyproject.toml
Labels: dependencies, documentation, enhancement

#42 Update publish.yml to remove || true
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#45 Fix publish.yml repo name
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#46 Update publish.yml to GPT4o-08-06
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#47 Update docstrings for tests
  tests/test_conv2d.py
  tests/test_matmul.py
  tests/test_relu.py
  tests/test_utils.py
  thop/__init__.py
Labels: documentation, enhancement

#49 Update publish.yml
  .github/workflows/publish.yml
  thop/__init__.py
Labels: enhancement

#50 Use PAT for PR details
  .github/workflows/publish.yml
  thop/__init__.py
Labels: dependencies, enhancement

#51 Add https://www.reddit.com/r/Ultralytics/ badge
  README.md
Labels: documentation, enhancement

#52 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#53 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement
