Repository ultralytics/thop, pull requests merged in 2025-01, with the labels that each got.

#78 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#79 Standardize license headers in Python files
  benchmark/evaluate_famous_models.py
  benchmark/evaluate_rnn_models.py
  tests/__init__.py
  tests/test_conv2d.py
  tests/test_matmul.py
  tests/test_relu.py
  tests/test_utils.py
  thop/__init__.py
  thop/fx_profile.py
  thop/profile.py
  thop/rnn_hooks.py
  thop/utils.py
  thop/vision/__init__.py
  thop/vision/basic_hooks.py
  thop/vision/calc_func.py
Labels: documentation

#80 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
  .github/workflows/publish.yml
  pyproject.toml
Labels: documentation, devops

#81 Update pyproject.toml
  pyproject.toml
Labels: documentation

#82 Update __init__.py
  thop/__init__.py
Labels: dependencies, enhancement
